### ISSUE TITLE
关于自建门户上传图片后依然无显示

### ISSUE THREAD

**Issue by beiyaoo** [NoneMeme/memebox#3]
本人使用此模板新建了一个仓库 上传图片后action正常运行
![image](https://user-images.githubusercontent.com/98569420/229051967-79e86937-e704-4370-9840-d13f92e1c6ed.png)
但网站无显示 过了几分钟重试和尝试清除浏览器缓存依然无效
![image](https://user-images.githubusercontent.com/98569420/229052155-1c92da9e-eeb1-4c8d-87f3-56af687bcd54.png)

**Comment by NCBM** [comment]
请检查 `static/scripts/config.js` 确认图片已被添加。若未被添加，请报告；若已被添加，则可能受到 CDN 缓存的影响，可能需要等待更长时间。

**Comment by beiyaoo** [comment]
config.js内有修改 请问cdn是否可以更换 如果可以在哪里更换 主要是昨天晚上上传图片到现在依然没有显示....

**Comment by NCBM** [comment]
> config.js内有修改 请问cdn是否可以更换 如果可以在哪里更换 主要是昨天晚上上传图片到现在依然没有显示....

很抱歉，我对此并不擅长。

另外你可以单独检查一下通过raw链接能否访问到图片。

**Comment by beiyaoo** [comment]
如何查看（

**Comment by NCBM** [comment]
根据文件位置在门户地址后追加文件路径（

比如 xxxxx.url/meme/image1.jpg

**Comment by beiyaohhhc** [comment]
可以正常访问

**Comment by beiyaoo** [comment]
追加路径后可以正常显示 但未追加路径依然无显示

**Comment by beiyaoo** [comment]
找到问题所在 在`/static/scripts/index.js `文件中
代码`const development =
    
    location.host.search(/beiyao\.icu/) === -1 `需要改为自己所绑定的域名
